from django.urls import path, include
from . import views
from django.contrib import admin


urlpatterns = [
    path('', views.index, name='index'),
    path('alllop/', views.lop_list, name='lop_list'),
    #path('', views.index, name='t_clas'),
    path('teacher/<slug:teacher_id>/<int:choice>/Classes/',
         views.t_clas, name='t_clas'),
    path('teacher/<slug:teacher_id>/t_timetable/',
         views.t_timetable, name='t_timetable'),
    path('allteachers/', views.teacher_list, name='teacher_list'),
    path('allsv/', views.sv_list, name='sv_list'),
    path('allgv/', views.gv_list, name='gv_list'),
    path('import-mh-dm/', views.import_monhoc_dm, name='import_monhoc_dm'),
    path('import-lopsv/<int:lop_id>/', views.import_lopsv, name='import_lopsv'),
    path('import-gv/', views.import_gv, name='import_gv'),
    path('export-gv/', views.export_gv, name='export_gv'),
    path('allctdt/', views.ctdt_list, name='ctdt_list'),
    path('alllop/', views.lop_list, name='lop_list'),
    path('alllichhoc/', views.lichhoc_list, name='lichhoc_list'),
    path('registration/', views.create_lichhoc, name='create_lichhoc'),
    path('CreateLichhoclm/<int:lopmh_id>/', views.create_lichhoclm, name='create_lichhoclm'),
    path('lopsv/<int:lop_id>/', views.sv_lop, name='svlop_list'),
    path('lichhoc/<int:lop_id>/', views.lichhoc_lop, name='lichhoclop_list'),
    path('lichhoclmh/<int:lopmh_id>/', views.lichhoc_lopmh, name='lichhoclopmh_list'),
    path('hocphi/<int:lop_id>/', views.hocphi_lop, name='hocphi_list'),
    path('monhoc/<int:lop_id>/', views.lop_monhoc, name='lop_monhoc'),
    path('<int:ctdt_id>/', views.single_ctdtmonhoc, name='lop_ctdtmonhoc'),
    path('ctdt_monhoc/<int:ctdt_id>/', views.ctdt_monhoc, name='ctdt_monhoc'),
    path('<int:ctdt_id>/', views.single_ctdtmonhoc, name='single_ctdtmonhoc'),
    path('CreateDiemdanh/<int:lh_id>', views.create_diemdanh, name='create_diemdanh'),
    path('CreateHocphi/<int:lh_id>', views.create_hocphi, name='create_hocphi'),
    path('CreateCtdtMonhoc/', views.create_ctdtmonhoc, name='create_ctdtmonhoc'),
    path('CreateLopMonhoc/<int:lop_id>/', views.create_lopmonhoc, name='create_lopmonhoc'),
    path('EditLopMonhoc/<int:lmh_id>/', views.edit_lopmonhoc, name='edit_lopmonhoc'),
    path('HistoryLopMonhoc/<int:lmh_id>/', views.history_lopmonhoc, name='history_lopmonhoc'),
    path('EditLichhoc/<int:lh_id>/', views.edit_lichhoc, name='edit_lichhoc'),

    path('CreateDiem/<int:lh_id>/', views.create_diem, name='create_diem'),
    path('CreateLop/', views.create_lop, name='create_lop'),
    path('EditLop/<int:lop_id>/', views.edit_lop, name='edit_lop'),
    path('CreateSinhvien/', views.create_sv, name='create_sv'),
    path('EditSinhvien/<int:sv_id>/', views.edit_sv, name='edit_sv'),
    path('CreateGiaovien/', views.create_gv, name='create_gv'),
    path('EditGiaovien/<int:gv_id>/', views.edit_gv, name='edit_gv'),
    path('CreateCtdt/', views.create_ctdt, name='create_ctdt'),
    path('<int:teacher_id>/', views.single_teacher, name='single_teacher'),
    path('hs81/<int:lop_id>/', views.single_hs81lop, name='single_hs81lop'),
    path('lop81-lst/<int:lop_id>/', views.lop81_lst, name='lop81-lst'),
    path('diemdanh/<int:lh_id>', views.diemdanh_lop ,name='diemdanh_list'),
    path('registration/', views.create_teacher, name='create_teacher'),
    path('edit/<int:pk>', views.edit_teacher, name='edit_teacher'),
    path('alldiem/<int:lop_id>/', views.diem_lop, name='diem-lop_list'),
    path('diemlmh/<int:lmh_id>/', views.diem_lmh, name='diem-lmh'),
    path('diemlmh-lst/<int:lmh_id>/', views.diem_lmh_lst, name='diem-lmh-lst'),
    path('diemlmh-dtp/<int:lmh_id>/<int:dtp_id>/', views.diem_lmh_dtp, name='diem-lmh-dtp'),
    path('lop81-hk/<int:lop_id>/<int:hk_ma>/', views.lop81_hk, name='lop81-hk'),
    path('lophp-hk/<int:lop_id>/<int:hk_ma>/', views.lophp_hk, name='lophp-hk'),
    path('delete/<int:teacher_id>', views.delete_teacher, name='delete_teacher'),
    path('react', views.react, name='react'),
]
admin.site.site_url = None
admin.site.site_header = 'My Site'
