# Generated by Django 4.2 on 2024-12-28 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ctdt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('khoa', models.CharField(max_length=100)),
                ('khoahoc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiemdanhAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=100)),
                ('diachi', models.CharField(max_length=300)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hocky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.IntegerField(default=1)),
                ('ten', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HocphiStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.IntegerField(default=1)),
                ('ten', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hsgv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('hoten', models.CharField(max_length=100)),
                ('diachi', models.CharField(blank=True, max_length=100)),
                ('quequan', models.CharField(blank=True, max_length=100)),
                ('sdt', models.CharField(blank=True, max_length=100)),
                ('gioitinh', models.CharField(blank=True, max_length=100)),
                ('cccd', models.CharField(blank=True, max_length=100)),
                ('tthn', models.CharField(blank=True, max_length=100)),
                ('dantoc', models.CharField(blank=True, max_length=100)),
                ('loaihd', models.CharField(blank=True, max_length=100)),
                ('hocham', models.CharField(blank=True, max_length=100)),
                ('hocvi', models.CharField(blank=True, max_length=100)),
                ('stk', models.CharField(blank=True, max_length=100)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('thoihanhd', models.DateField(blank=True, default=None)),
                ('hsgv', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Loaidiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('ghichu', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(max_length=100)),
                ('ten', models.CharField(max_length=100)),
                ('trungtam', models.CharField(max_length=100)),
                ('ctdt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.ctdt')),
            ],
        ),
        migrations.CreateModel(
            name='Monhoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(max_length=100)),
                ('ten', models.CharField(max_length=100)),
                ('chuongtrinh', models.CharField(max_length=100)),
                ('sotinchi', models.IntegerField()),
                ('sogio_lt', models.IntegerField()),
                ('sogio_th', models.IntegerField()),
                ('sogio_kt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SvStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.IntegerField(default=1)),
                ('ten', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDeptInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('passing_year', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('salary', models.IntegerField()),
                ('dept_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.teacherdeptinfo')),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.teachersubinfo')),
            ],
        ),
        migrations.CreateModel(
            name='LopMonhoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaystart', models.DateField(blank=True, default=None)),
                ('ngayend', models.DateField(blank=True, default=None)),
                ('status', models.CharField(max_length=50)),
                ('hsdt', models.CharField(blank=True, default='', max_length=500)),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.lop')),
                ('monhoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.monhoc')),
            ],
        ),
        migrations.CreateModel(
            name='Lichhoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trungtam', models.CharField(blank=True, max_length=100)),
                ('diadiem', models.CharField(blank=True, max_length=100)),
                ('thoigian', models.DateField()),
                ('sogio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hoctu', models.CharField(blank=True, max_length=100)),
                ('hoc_from_gio', models.IntegerField(blank=True)),
                ('hoc_from_phut', models.IntegerField(blank=True)),
                ('hoc_to_gio', models.IntegerField(blank=True)),
                ('hoc_to_phut', models.IntegerField(blank=True)),
                ('ghichu', models.TextField(blank=True, default='')),
                ('giaovien', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sms.hsgv')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.lop')),
                ('monhoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.monhoc')),
            ],
        ),
        migrations.CreateModel(
            name='Hssv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=100)),
                ('lop', models.CharField(max_length=100)),
                ('namsinh', models.DateField()),
                ('gioitinh', models.CharField(blank=True, max_length=30)),
                ('dantoc', models.CharField(blank=True, max_length=30)),
                ('noisinh', models.CharField(blank=True, max_length=200)),
                ('quequan', models.CharField(blank=True, max_length=200)),
                ('diachi', models.CharField(blank=True, max_length=200)),
                ('xa', models.CharField(blank=True, max_length=100)),
                ('huyen', models.CharField(blank=True, max_length=100)),
                ('tinh', models.CharField(blank=True, max_length=100)),
                ('cccd', models.CharField(blank=True, max_length=100)),
                ('hotenbo', models.CharField(blank=True, max_length=200)),
                ('hotenme', models.CharField(blank=True, max_length=200)),
                ('sdths', models.CharField(blank=True, max_length=100)),
                ('sdtph', models.CharField(blank=True, max_length=100)),
                ('hs81_1', models.CharField(blank=True, max_length=30)),
                ('hs81_2', models.CharField(blank=True, max_length=30)),
                ('hs81_3', models.CharField(blank=True, max_length=30)),
                ('hs81_4', models.CharField(blank=True, max_length=30)),
                ('hs81_5', models.CharField(blank=True, max_length=30)),
                ('hs81_6', models.CharField(blank=True, max_length=30)),
                ('hs81_7', models.CharField(blank=True, max_length=30)),
                ('hs81_8', models.CharField(blank=True, max_length=30)),
                ('hs81_9', models.CharField(blank=True, max_length=30)),
                ('hs81_10', models.CharField(blank=True, max_length=30)),
                ('hs81_11', models.CharField(blank=True, max_length=30)),
                ('hs81_12', models.CharField(blank=True, max_length=30)),
                ('hs81_13', models.CharField(blank=True, max_length=30)),
                ('ghichu', models.CharField(blank=True, max_length=500)),
                ('malop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.lop')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.svstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Hs81',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hk', models.IntegerField()),
                ('dondn', models.CharField(default='', max_length=50)),
                ('cntn', models.CharField(default='', max_length=50)),
                ('bangtn', models.CharField(default='', max_length=50)),
                ('xnct', models.CharField(default='', max_length=50)),
                ('cccd', models.CharField(default='', max_length=50)),
                ('cccdbo', models.CharField(default='', max_length=50)),
                ('cccdme', models.CharField(default='', max_length=50)),
                ('gsk', models.CharField(default='', max_length=50)),
                ('ghichu', models.CharField(default='', max_length=100)),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.lop')),
                ('sv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hssv')),
            ],
        ),
        migrations.CreateModel(
            name='Hocphi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hk', models.IntegerField()),
                ('thoigian', models.DateField(blank=True)),
                ('sotien', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('ghichu', models.TextField(blank=True, default='')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.lop')),
                ('sv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hssv')),
            ],
        ),
        migrations.CreateModel(
            name='Diemthanhphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.IntegerField()),
                ('monhoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.monhoc')),
                ('sv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hssv')),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.loaidiem')),
            ],
        ),
        migrations.CreateModel(
            name='Diemdanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghichu', models.CharField(blank=True, default='', max_length=300)),
                ('lichhoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.lichhoc')),
                ('sv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hssv')),
            ],
        ),
        migrations.CreateModel(
            name='CtdtMonhoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hocky', models.IntegerField()),
                ('ctdt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.ctdt')),
                ('monhoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.monhoc')),
            ],
        ),
    ]
