# Generated by Django 5.1.5 on 2025-03-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalttgv',
            name='sotiet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ttgv',
            name='sotiet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
