# Generated by Django 4.2 on 2025-10-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallocation',
            old_name='user',
            new_name='chu',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='user',
            new_name='chu',
        ),
    ]
