# Generated by Django 4.2 on 2025-03-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhsgv',
            name='hs_bd',
        ),
        migrations.RemoveField(
            model_name='hsgv',
            name='hs_bd',
        ),
        migrations.AlterField(
            model_name='historicalhp81',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhp81',
            name='thoigian',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhs81',
            name='ghichu',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhs81',
            name='thoigian',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='bhxh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='cccd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='cn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='diachi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='dongbhxh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='ghichu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='hs_btn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='hs_cc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='hs_ccta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='hs_ccth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='hs_syll',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='mst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='namsinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='nganhtn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='ngaycap',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='ngayhh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='ngayky',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='nh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='noicap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='sdt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='shdtg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='stk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='truongtn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsns',
            name='cccd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsns',
            name='diachi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsns',
            name='ghichu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsns',
            name='gioitinh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsns',
            name='quequan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsns',
            name='sdt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='cccd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='dantoc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='diachi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='ghichu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='gioitinh',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='hotenbo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='hotenme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='huyen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='namsinh',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='noisinh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='quequan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='sdths',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='sdtph',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='tinh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='xa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallichhoc',
            name='diadiem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallichhoc',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicallichhoc',
            name='trungtam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalloaidiem',
            name='ten',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallophk',
            name='end_hk',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicallophk',
            name='start_hk',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='ngayend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='ngaystart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmonhoc',
            name='sogio_kt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalmonhoc',
            name='sogio_lt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalmonhoc',
            name='sogio_th',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalttgv',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hp81',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hp81',
            name='thoigian',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='ghichu',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='thoigian',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='bhxh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='cccd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='cn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='diachi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='dongbhxh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='ghichu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='hs_btn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='hs_cc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='hs_ccta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='hs_ccth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='hs_syll',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='mst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='namsinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='nganhtn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='ngaycap',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='ngayhh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='ngayky',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='nh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='noicap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='sdt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='shdtg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='stk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='truongtn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsns',
            name='cccd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsns',
            name='diachi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsns',
            name='ghichu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hsns',
            name='gioitinh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsns',
            name='quequan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hsns',
            name='sdt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='cccd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='dantoc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='diachi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='ghichu',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='gioitinh',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='hotenbo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='hotenme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='huyen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='namsinh',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='noisinh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='quequan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='sdths',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='sdtph',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='tinh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='xa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='diadiem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='giaovien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.hsgv'),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='trungtam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loaidiem',
            name='ten',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logdiem',
            name='capnhat_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lophk',
            name='end_hk',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lophk',
            name='start_hk',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='ngayend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='ngaystart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='sogio_kt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='sogio_lt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='sogio_th',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ttgv',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
