# Generated by Django 4.2 on 2025-04-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhp81',
            name='sotien1',
            field=models.TextField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhp81',
            name='sotien2',
            field=models.TextField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicalttgv',
            name='sotien1',
            field=models.TextField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicalttgv',
            name='sotien2',
            field=models.TextField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='hp81',
            name='sotien1',
            field=models.TextField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='hp81',
            name='sotien2',
            field=models.TextField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='ttgv',
            name='sotien1',
            field=models.TextField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='ttgv',
            name='sotien2',
            field=models.TextField(blank=True, default='', max_length=11, null=True),
        ),
    ]
