# Generated by Django 4.2 on 2025-03-20 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctdtmonhoc',
            name='ctdt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.ctdt'),
        ),
        migrations.AlterField(
            model_name='ctdtmonhoc',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.monhoc'),
        ),
        migrations.AlterField(
            model_name='diemdanh',
            name='lichhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.lichhoc'),
        ),
        migrations.AlterField(
            model_name='diemdanh',
            name='sv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hssv'),
        ),
        migrations.AlterField(
            model_name='diemthanhphan',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.logdiem', verbose_name='ID Log'),
        ),
        migrations.AlterField(
            model_name='diemthanhphan',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.monhoc', verbose_name='Môn học'),
        ),
        migrations.AlterField(
            model_name='diemthanhphan',
            name='sv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hssv', verbose_name='Học viên'),
        ),
        migrations.AlterField(
            model_name='diemthanhphan',
            name='tp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.loaidiem', verbose_name='Điểm Thành phần'),
        ),
        migrations.AlterField(
            model_name='giayto_hs81',
            name='hs81',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hs81'),
        ),
        migrations.AlterField(
            model_name='giayto_hs81',
            name='softfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='gvlmh',
            name='gv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hsgv', verbose_name='Giáo viên'),
        ),
        migrations.AlterField(
            model_name='gvlmh',
            name='lopmh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.lopmonhoc', verbose_name='Lớp môn học'),
        ),
        migrations.AlterField(
            model_name='gvlop',
            name='gv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hsgv'),
        ),
        migrations.AlterField(
            model_name='gvlop',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.lop'),
        ),
        migrations.AlterField(
            model_name='gvmonhoc',
            name='gv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hsgv'),
        ),
        migrations.AlterField(
            model_name='gvmonhoc',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.monhoc'),
        ),
        migrations.AlterField(
            model_name='hocphi',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.lop'),
        ),
        migrations.AlterField(
            model_name='hocphi',
            name='sv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hssv'),
        ),
        migrations.AlterField(
            model_name='hp81',
            name='hk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hocky'),
        ),
        migrations.AlterField(
            model_name='hp81',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hocphistatus'),
        ),
        migrations.AlterField(
            model_name='hp81',
            name='sv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hssv'),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='hk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hocky'),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='sv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hssv'),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hsns',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='lop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.lop'),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='sms.svstatus'),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='giaovien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.hsgv'),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.lop'),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.monhoc'),
        ),
        migrations.AlterField(
            model_name='lop',
            name='ctdt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.ctdt', verbose_name='Chương trình đào tạo'),
        ),
        migrations.AlterField(
            model_name='lop',
            name='trungtam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.trungtam', verbose_name='Trung tâm'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='sms.hocky'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.lop'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.monhoc'),
        ),
        migrations.AlterField(
            model_name='nslop',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.lop'),
        ),
        migrations.AlterField(
            model_name='nslop',
            name='ns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hsns'),
        ),
        migrations.AlterField(
            model_name='nsphong',
            name='ns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hsns'),
        ),
        migrations.AlterField(
            model_name='nsphong',
            name='phong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.phong'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='dept_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.teacherdeptinfo'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.teachersubinfo'),
        ),
        migrations.AlterField(
            model_name='ttgv',
            name='gv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hsgv'),
        ),
        migrations.AlterField(
            model_name='ttgv',
            name='lopmh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.lopmonhoc'),
        ),
    ]
