# Generated by Django 4.2 on 2024-12-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diemdanh',
            name='ghichu',
        ),
        migrations.AddField(
            model_name='diemdanh',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
