# Generated by Django 4.2 on 2025-05-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_historicalhp81_sotien1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoclai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmh', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.lopmonhoc')),
                ('sv', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.hssv')),
            ],
            options={
                'verbose_name': 'Thi lại',
                'verbose_name_plural': 'Danh sác Thi lại',
                'ordering': ['-id'],
                'unique_together': {('sv', 'lmh')},
            },
        ),
    ]
