# Generated by Django 4.2 on 2025-03-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_remove_historicalhsgv_hs_bd_remove_hsgv_hs_bd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhsgv',
            name='hs_bd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hsgv',
            name='hs_bd',
            field=models.BooleanField(default=False),
        ),
    ]
