# Generated by Django 4.2 on 2024-12-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_remove_diemdanh_ghichu_diemdanh_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaidiem',
            name='ghichu',
        ),
        migrations.AddField(
            model_name='loaidiem',
            name='ma',
            field=models.IntegerField(default=1),
        ),
    ]
