# Generated by Django 4.2 on 2025-10-07 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0002_rename_user_historicallocation_chu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='chu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
