# Generated by Django 4.2 on 2025-03-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_ctdtmonhoc_ctdt_alter_ctdtmonhoc_monhoc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallichhoc',
            name='lop',
        ),
        migrations.RemoveField(
            model_name='historicallichhoc',
            name='monhoc',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='lop',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='monhoc',
        ),
        migrations.AddField(
            model_name='historicallichhoc',
            name='lmh',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.lopmonhoc'),
        ),
        migrations.AddField(
            model_name='lichhoc',
            name='lmh',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='sms.lopmonhoc'),
        ),
    ]
