# Generated by Django 4.2 on 2025-10-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_location_chu'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhouse',
            name='ten',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên nhà trọ'),
        ),
        migrations.AddField(
            model_name='house',
            name='ten',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên nhà trọ'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='interval',
            field=models.CharField(choices=[('1 tháng', '1 tháng'), ('3 tháng', '3 tháng'), ('6 tháng', '6 tháng'), ('12 tháng', '12 tháng'), ('Khác', 'Khác')], max_length=100, verbose_name='Số tháng/kỳ thanh toán'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='loainha',
            field=models.CharField(choices=[('Nguyên căn', 'Nguyên căn'), ('Căn hộ', 'Căn hộ'), ('Khác', 'Khác')], verbose_name='Loại nhà'),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='xp',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.xaphuong', verbose_name='Xã/Phường - Tỉnh/Thành phố'),
        ),
        migrations.AlterField(
            model_name='house',
            name='interval',
            field=models.CharField(choices=[('1 tháng', '1 tháng'), ('3 tháng', '3 tháng'), ('6 tháng', '6 tháng'), ('12 tháng', '12 tháng'), ('Khác', 'Khác')], max_length=100, verbose_name='Số tháng/kỳ thanh toán'),
        ),
        migrations.AlterField(
            model_name='house',
            name='loainha',
            field=models.CharField(choices=[('Nguyên căn', 'Nguyên căn'), ('Căn hộ', 'Căn hộ'), ('Khác', 'Khác')], verbose_name='Loại nhà'),
        ),
        migrations.AlterField(
            model_name='location',
            name='xp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='sms.xaphuong', verbose_name='Xã/Phường - Tỉnh/Thành phố'),
        ),
    ]
