# Generated by Django 4.2 on 2024-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_remove_loaidiem_ghichu_loaidiem_ma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichhoc',
            name='hoc_from_gio',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='hoc_from_phut',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='hoc_to_gio',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='hoc_to_phut',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='hoctu',
        ),
        migrations.RemoveField(
            model_name='lichhoc',
            name='sogio',
        ),
        migrations.AddField(
            model_name='lichhoc',
            name='sotiet',
            field=models.IntegerField(default=1),
        ),
    ]
