# Generated by Django 4.2 on 2025-03-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_historicalhsgv_hs_bd_hsgv_hs_bd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhsgv',
            name='trinhdo',
            field=models.CharField(blank=True, choices=[('Cử nhân', 'Cử nhân'), ('Thạc sĩ', 'Thạc sĩ'), ('Tiến sĩ', 'Tiến sĩ'), ('Giáo sư', 'Giáo sư')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='trinhdo',
            field=models.CharField(blank=True, choices=[('Cử nhân', 'Cử nhân'), ('Thạc sĩ', 'Thạc sĩ'), ('Tiến sĩ', 'Tiến sĩ'), ('Giáo sư', 'Giáo sư')], max_length=50, null=True),
        ),
    ]
