# Generated by Django 4.2 on 2025-05-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_hoclai'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemthanhphan',
            name='lmh',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.lopmonhoc', verbose_name='Lớp Môn học'),
        ),
        migrations.AddField(
            model_name='historicaldiemthanhphan',
            name='lmh',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.lopmonhoc', verbose_name='Lớp Môn học'),
        ),
    ]
