# Generated by Django 4.2 on 2025-02-19 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_historicalhp81_hs81_ghichu_historicalhp81_hs81_st_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhp81',
            name='hs81_st',
            field=models.CharField(choices=[('Thiếu', 'Thiếu'), ('Đủ', 'Đủ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalhp81',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.hocphistatus'),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.svstatus'),
        ),
        migrations.AlterField(
            model_name='hp81',
            name='hs81_st',
            field=models.CharField(choices=[('Thiếu', 'Thiếu'), ('Đủ', 'Đủ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hp81',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hocphistatus'),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.svstatus'),
        ),
    ]
