# Generated by Django 4.2 on 2025-03-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_remove_historicallichhoc_lop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloaidiem',
            name='ma',
            field=models.CharField(default='KTTX'),
        ),
        migrations.AlterField(
            model_name='loaidiem',
            name='ma',
            field=models.CharField(default='KTTX'),
        ),
    ]
