# Generated by Django 4.2 on 2024-12-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_remove_lichhoc_hoc_from_gio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhoc',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
