# Generated by Django 4.2 on 2025-10-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_historicalhouse_ten_house_ten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouse',
            name='ten',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên nhà trọ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='loc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.location'),
        ),
        migrations.AlterField(
            model_name='house',
            name='ten',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên nhà trọ'),
        ),
    ]
