# Generated by Django 4.2 on 2025-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_historicalhsgv_trinhdo_alter_hsgv_trinhdo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalttgv',
            name='sotien1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalttgv',
            name='sotien2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ttgv',
            name='sotien1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ttgv',
            name='sotien2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
