# Generated by Django 4.2 on 2025-02-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_historicalhp81_hs81_st_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhp81',
            name='hs81_ghichu',
        ),
        migrations.RemoveField(
            model_name='hp81',
            name='hs81_ghichu',
        ),
    ]
