# Generated by Django 4.2 on 2025-05-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_diemthanhphan_lmh_historicaldiemthanhphan_lmh'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemthanhphan',
            name='att',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicaldiemthanhphan',
            name='att',
            field=models.IntegerField(default=1),
        ),
    ]
