# Generated by Django 4.2 on 2025-10-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_historicalhouse_ten_alter_house_loc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluploadedfile',
            name='house',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.house'),
        ),
        migrations.AddField(
            model_name='historicaluploadedfile',
            name='loc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.location'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.house'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.location'),
        ),
    ]
