# Generated by Django 4.2 on 2025-03-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_historicalttgv_sotien1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhp81',
            name='sotien1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhp81',
            name='sotien2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hp81',
            name='sotien1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hp81',
            name='sotien2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
