# Generated by Django 4.2 on 2025-05-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_diemthanhphan_att_historicaldiemthanhphan_att'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemthanhphan',
            name='diem',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm'),
        ),
        migrations.AlterField(
            model_name='historicaldiemthanhphan',
            name='diem',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm'),
        ),
    ]
