# Generated by Django 4.2 on 2025-02-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_remove_historicalhp81_hs81_ghichu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhssv',
            name='image',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalhssv',
            name='image_data',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='hssv',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hssv',
            name='image_data',
            field=models.BinaryField(null=True),
        ),
    ]
