# Generated by Django 4.2 on 2024-12-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_lichhoc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemthanhphan',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
