# Generated by Django 4.2 on 2025-10-07 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0006_historicaluploadedfile_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRenter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('chu_id', models.BigIntegerField(null=True)),
                ('ma', models.CharField(max_length=100, verbose_name='Mã')),
                ('hoten', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('sdt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số điện thoại')),
                ('cccd', models.CharField(blank=True, max_length=100, null=True, verbose_name='CCCD')),
                ('ngaycap', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('noicap', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('mst', models.CharField(blank=True, max_length=100, null=True, verbose_name='MS Thuế cá nhân')),
                ('ghichu', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ghi chú')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Người thuê',
                'verbose_name_plural': 'historical Danh sách Người thuê',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chu_id', models.BigIntegerField(null=True)),
                ('ma', models.CharField(max_length=100, verbose_name='Mã')),
                ('hoten', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('sdt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Số điện thoại')),
                ('cccd', models.CharField(blank=True, max_length=100, null=True, verbose_name='CCCD')),
                ('ngaycap', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('noicap', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('mst', models.CharField(blank=True, max_length=100, null=True, verbose_name='MS Thuế cá nhân')),
                ('ghichu', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ghi chú')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Người thuê',
                'verbose_name_plural': 'Danh sách Người thuê',
                'ordering': ['ma'],
                'unique_together': {('ma',)},
            },
        ),
    ]
