# Generated by Django 4.2 on 2025-03-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_alter_historicalhp81_sotien1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemthanhphan',
            name='diem',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicaldiemthanhphan',
            name='diem',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
