# Generated by Django 4.2 on 2025-02-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_historicalhssv_image_historicalhssv_image_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhssv',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='hssv',
            name='image_data',
        ),
        migrations.AlterField(
            model_name='hssv',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
