# Generated by Django 4.2 on 2024-12-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_diemthanhphan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocphi',
            name='hpstatus',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hs81',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hocphi',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
