# Generated by Django 4.2 on 2024-12-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_hocphi_hpstatus_hs81_status_alter_hocphi_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocphi',
            name='thoigian',
            field=models.DateField(blank=True, default=None),
        ),
    ]
