# Generated by Django 4.2 on 2025-05-22 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0007_historicallopmonhoc_mhdk_lopmonhoc_mhdk'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDiemTk',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sv_id', models.IntegerField(default=0, verbose_name='Mã học viên')),
                ('ma', models.CharField(default='', max_length=100, verbose_name='Mã học viên')),
                ('ten', models.CharField(default='', max_length=100, verbose_name='Họ tên học viên')),
                ('lmh_id', models.IntegerField(default=0, verbose_name='Mã lớp môn học')),
                ('monhoc_id', models.IntegerField(default=0, verbose_name='Mã môn học')),
                ('monhoc', models.CharField(default='', max_length=100, verbose_name='Tên môn học')),
                ('tc', models.IntegerField(default=0, verbose_name='Số tín chỉ')),
                ('tbm', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm trung bình môn')),
                ('tbmc', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm trung bình môn có điều kiện')),
                ('tbm4', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm trung bình môn 4')),
                ('tbmkt', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm trung bình môn kỳ thi')),
                ('kttx1', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTTX 1')),
                ('n_kttx1', models.BooleanField(default=False)),
                ('kttx2', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTTX 2')),
                ('n_kttx2', models.BooleanField(default=False)),
                ('kttx3', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTTX 3')),
                ('n_kttx3', models.BooleanField(default=False)),
                ('ktdk1', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTDK 1')),
                ('n_ktdk1', models.BooleanField(default=False)),
                ('ktdk2', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTDK 2')),
                ('n_ktdk2', models.BooleanField(default=False)),
                ('ktdk3', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTDK 3')),
                ('n_ktdk3', models.BooleanField(default=False)),
                ('ktkt1', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTKT 1')),
                ('n_ktkt1', models.BooleanField(default=False)),
                ('ktkt2', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTKT 2')),
                ('n_ktkt2', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Điểm tổng kết môn học',
                'verbose_name_plural': 'historical Điểm tổng kết môn học',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DiemTk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sv_id', models.IntegerField(default=0, verbose_name='Mã học viên')),
                ('ma', models.CharField(default='', max_length=100, verbose_name='Mã học viên')),
                ('ten', models.CharField(default='', max_length=100, verbose_name='Họ tên học viên')),
                ('lmh_id', models.IntegerField(default=0, verbose_name='Mã lớp môn học')),
                ('monhoc_id', models.IntegerField(default=0, verbose_name='Mã môn học')),
                ('monhoc', models.CharField(default='', max_length=100, verbose_name='Tên môn học')),
                ('tc', models.IntegerField(default=0, verbose_name='Số tín chỉ')),
                ('tbm', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm trung bình môn')),
                ('tbmc', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm trung bình môn có điều kiện')),
                ('tbm4', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm trung bình môn 4')),
                ('tbmkt', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm trung bình môn kỳ thi')),
                ('kttx1', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTTX 1')),
                ('n_kttx1', models.BooleanField(default=False)),
                ('kttx2', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTTX 2')),
                ('n_kttx2', models.BooleanField(default=False)),
                ('kttx3', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTTX 3')),
                ('n_kttx3', models.BooleanField(default=False)),
                ('ktdk1', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTDK 1')),
                ('n_ktdk1', models.BooleanField(default=False)),
                ('ktdk2', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTDK 2')),
                ('n_ktdk2', models.BooleanField(default=False)),
                ('ktdk3', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTDK 3')),
                ('n_ktdk3', models.BooleanField(default=False)),
                ('ktkt1', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTKT 1')),
                ('n_ktkt1', models.BooleanField(default=False)),
                ('ktkt2', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm KTKT 2')),
                ('n_ktkt2', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Điểm tổng kết môn học',
                'verbose_name_plural': 'Điểm tổng kết môn học',
                'ordering': ['id'],
                'unique_together': {('sv_id', 'lmh_id')},
            },
        ),
    ]
