# Generated by Django 4.2 on 2025-03-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_alter_diemthanhphan_diem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemthanhphan',
            name='diem',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicaldiemthanhphan',
            name='diem',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
