# Generated by Django 4.2 on 2025-10-08 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0007_historicalrenter_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrenter',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalrenter',
            name='ma',
            field=models.CharField(null=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='ma',
            field=models.CharField(null=True, verbose_name='Mã'),
        ),
        migrations.CreateModel(
            name='HouseRenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_from', models.DateField(blank=True, null=True, verbose_name='Thuê từ ngày')),
                ('rent_to', models.DateField(blank=True, null=True, verbose_name='Thuê đến ngày')),
                ('ghichu', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ghi chú')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.house')),
                ('renter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.renter')),
            ],
            options={
                'verbose_name': 'Người thuê - Nhà trọ',
                'verbose_name_plural': 'Người thuê - Nhà trọ',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHouseRenter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rent_from', models.DateField(blank=True, null=True, verbose_name='Thuê từ ngày')),
                ('rent_to', models.DateField(blank=True, null=True, verbose_name='Thuê đến ngày')),
                ('ghichu', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ghi chú')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.house')),
                ('renter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.renter')),
            ],
            options={
                'verbose_name': 'historical Người thuê - Nhà trọ',
                'verbose_name_plural': 'historical Người thuê - Nhà trọ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
