# Generated by Django 4.2 on 2025-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_historicaldiemtk_diemtk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemtk',
            name='tbmc',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='historicaldiemtk',
            name='tbmc',
            field=models.CharField(default='', max_length=5),
        ),
    ]
