# Generated by Django 4.2 on 2025-10-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_alter_historicalrenter_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouserenter',
            name='ghichu',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='houserenter',
            name='ghichu',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Ghi chú'),
        ),
    ]
