# Generated by Django 4.2 on 2025-03-14 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_alter_diemthanhphan_diem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctdt',
            options={'ordering': ['-id'], 'verbose_name': 'Danh mục CTĐT', 'verbose_name_plural': 'Danh mục CTĐT'},
        ),
        migrations.AlterModelOptions(
            name='ctdtmonhoc',
            options={'ordering': ['id'], 'verbose_name': 'Chương trình đào tạo môn học', 'verbose_name_plural': 'Chương trình đào tạo môn học'},
        ),
        migrations.AlterModelOptions(
            name='historicalctdt',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Danh mục CTĐT', 'verbose_name_plural': 'historical Danh mục CTĐT'},
        ),
        migrations.AlterModelOptions(
            name='historicalctdtmonhoc',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Chương trình đào tạo môn học', 'verbose_name_plural': 'historical Chương trình đào tạo môn học'},
        ),
        migrations.AlterModelOptions(
            name='historicalmonhoc',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Môn học', 'verbose_name_plural': 'historical Môn học'},
        ),
        migrations.AlterModelOptions(
            name='monhoc',
            options={'ordering': ['-id'], 'verbose_name': 'Môn học', 'verbose_name_plural': 'Môn học'},
        ),
    ]
