# Generated by Django 4.2 on 2025-01-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_alter_hocphi_thoigian'),
    ]

    operations = [
        migrations.AddField(
            model_name='hssv',
            name='msv',
            field=models.CharField(blank=True, default='TC0001', max_length=100),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='status',
            field=models.IntegerField(choices=[(1, 'Bình thường'), (2, 'Bảo lưu'), (3, 'Chuyển lớp'), (4, 'Nghỉ học')], default=1),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='status',
            field=models.CharField(choices=[('Lập kế hoạch', 'Lập kế hoạch'), ('Đã hoàn thành', 'Đã hoàn thành')], max_length=50),
        ),
    ]
