# Generated by Django 4.2 on 2025-03-14 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_alter_ctdt_options_alter_ctdtmonhoc_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctdt',
            options={'ordering': ['-id'], 'verbose_name': 'Chương trinh đào tạo', 'verbose_name_plural': 'Danh mục CTĐT'},
        ),
        migrations.AlterModelOptions(
            name='diemthanhphan',
            options={'ordering': ['sv', 'monhoc', 'tp'], 'verbose_name': 'Điểm thành phần', 'verbose_name_plural': 'Kết quả điểm thành phần'},
        ),
        migrations.AlterModelOptions(
            name='historicalctdt',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Chương trinh đào tạo', 'verbose_name_plural': 'historical Danh mục CTĐT'},
        ),
        migrations.AlterModelOptions(
            name='historicaldiemthanhphan',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Điểm thành phần', 'verbose_name_plural': 'historical Kết quả điểm thành phần'},
        ),
        migrations.AlterModelOptions(
            name='historicalhocky',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Học kỳ', 'verbose_name_plural': 'historical Danh mục Học kỳ'},
        ),
        migrations.AlterModelOptions(
            name='historicalhocphistatus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Trạng thái Học phí', 'verbose_name_plural': 'historical Danh mục Trạng thái Học phí'},
        ),
        migrations.AlterModelOptions(
            name='historicalloaidiem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Điểm thành phần', 'verbose_name_plural': 'historical Danh mục Điểm thành phần'},
        ),
        migrations.AlterModelOptions(
            name='historicallop',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Lớp', 'verbose_name_plural': 'historical Danh sác Lớp'},
        ),
        migrations.AlterModelOptions(
            name='historicallophk',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Lớp Học kỳ', 'verbose_name_plural': 'historical Lớp Học kỳ'},
        ),
        migrations.AlterModelOptions(
            name='historicallopmonhoc',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Lớp môn học', 'verbose_name_plural': 'historical Lớp môn học'},
        ),
        migrations.AlterModelOptions(
            name='historicalmonhoc',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Môn học', 'verbose_name_plural': 'historical Danh mục Môn học'},
        ),
        migrations.AlterModelOptions(
            name='historicalphong',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Phòng', 'verbose_name_plural': 'historical Danh mục Phòng'},
        ),
        migrations.AlterModelOptions(
            name='historicalsvstatus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Trạng thái học viên', 'verbose_name_plural': 'historical Danh mục Trạng thái học viên'},
        ),
        migrations.AlterModelOptions(
            name='historicaltrungtam',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Trung tâm', 'verbose_name_plural': 'historical Danh mục Trung tâm'},
        ),
        migrations.AlterModelOptions(
            name='hocky',
            options={'ordering': ['id'], 'verbose_name': 'Học kỳ', 'verbose_name_plural': 'Danh mục Học kỳ'},
        ),
        migrations.AlterModelOptions(
            name='hocphistatus',
            options={'ordering': ['id'], 'verbose_name': 'Trạng thái Học phí', 'verbose_name_plural': 'Danh mục Trạng thái Học phí'},
        ),
        migrations.AlterModelOptions(
            name='loaidiem',
            options={'ordering': ['-id'], 'verbose_name': 'Điểm thành phần', 'verbose_name_plural': 'Danh mục Điểm thành phần'},
        ),
        migrations.AlterModelOptions(
            name='lop',
            options={'ordering': ['-id'], 'verbose_name': 'Lớp', 'verbose_name_plural': 'Danh sác Lớp'},
        ),
        migrations.AlterModelOptions(
            name='lophk',
            options={'ordering': ['hk'], 'verbose_name': 'Lớp Học kỳ', 'verbose_name_plural': 'Lớp Học kỳ'},
        ),
        migrations.AlterModelOptions(
            name='lopmonhoc',
            options={'ordering': ['-id', '-ngaystart'], 'verbose_name': 'Lớp môn học', 'verbose_name_plural': 'Lớp môn học'},
        ),
        migrations.AlterModelOptions(
            name='monhoc',
            options={'ordering': ['-id'], 'verbose_name': 'Môn học', 'verbose_name_plural': 'Danh mục Môn học'},
        ),
        migrations.AlterModelOptions(
            name='phong',
            options={'ordering': ['id'], 'verbose_name': 'Phòng', 'verbose_name_plural': 'Danh mục Phòng'},
        ),
        migrations.AlterModelOptions(
            name='svstatus',
            options={'ordering': ['id'], 'verbose_name': 'Trạng thái học viên', 'verbose_name_plural': 'Danh mục Trạng thái học viên'},
        ),
        migrations.AlterModelOptions(
            name='trungtam',
            options={'ordering': ['id'], 'verbose_name': 'Trung tâm', 'verbose_name_plural': 'Danh mục Trung tâm'},
        ),
        migrations.AlterField(
            model_name='diemthanhphan',
            name='diem',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Điểm'),
        ),
        migrations.AlterField(
            model_name='diemthanhphan',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.logdiem', verbose_name='ID Log'),
        ),
        migrations.AlterField(
            model_name='diemthanhphan',
            name='monhoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.monhoc', verbose_name='Môn học'),
        ),
        migrations.AlterField(
            model_name='diemthanhphan',
            name='sv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hssv', verbose_name='Học viên'),
        ),
        migrations.AlterField(
            model_name='diemthanhphan',
            name='tp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.loaidiem', verbose_name='Điểm Thành phần'),
        ),
        migrations.AlterField(
            model_name='historicaldiemthanhphan',
            name='diem',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Điểm'),
        ),
        migrations.AlterField(
            model_name='historicaldiemthanhphan',
            name='log',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.logdiem', verbose_name='ID Log'),
        ),
        migrations.AlterField(
            model_name='historicaldiemthanhphan',
            name='monhoc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.monhoc', verbose_name='Môn học'),
        ),
        migrations.AlterField(
            model_name='historicaldiemthanhphan',
            name='sv',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.hssv', verbose_name='Học viên'),
        ),
        migrations.AlterField(
            model_name='historicaldiemthanhphan',
            name='tp',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.loaidiem', verbose_name='Điểm Thành phần'),
        ),
        migrations.AlterField(
            model_name='historicalhsgv',
            name='ghichu',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhsns',
            name='ghichu',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='ghichu',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalloaidiem',
            name='heso',
            field=models.IntegerField(default=1, verbose_name='Hệ số'),
        ),
        migrations.AlterField(
            model_name='historicalloaidiem',
            name='trunglap',
            field=models.IntegerField(default=1, verbose_name='Số lần cho điểm'),
        ),
        migrations.AlterField(
            model_name='historicallop',
            name='ctdt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.ctdt', verbose_name='Chương trình đào tạo'),
        ),
        migrations.AlterField(
            model_name='historicallop',
            name='ma',
            field=models.CharField(max_length=100, verbose_name='Mã Lớp'),
        ),
        migrations.AlterField(
            model_name='historicallop',
            name='ten',
            field=models.CharField(max_length=100, verbose_name='Tên Lớp'),
        ),
        migrations.AlterField(
            model_name='historicallop',
            name='trungtam',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.trungtam', verbose_name='Trung tâm'),
        ),
        migrations.AlterField(
            model_name='historicallophk',
            name='end_hk',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='historicallophk',
            name='hk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.hocky', verbose_name='Học kỳ'),
        ),
        migrations.AlterField(
            model_name='historicallophk',
            name='start_hk',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Hồ sơ đào tạo'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt1',
            field=models.BooleanField(default=False, verbose_name='Hồ sơ đào tạo 1'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt2',
            field=models.BooleanField(default=False, verbose_name='Hồ sơ đào tạo 2'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt3',
            field=models.BooleanField(default=False, verbose_name='Hồ sơ đào tạo 3'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt4',
            field=models.BooleanField(default=False, verbose_name='Hồ sơ đào tạo 4'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='ngayend',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='ngaystart',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='historicaltrungtam',
            name='ma',
            field=models.IntegerField(default=1, verbose_name='Mã Trung tâm'),
        ),
        migrations.AlterField(
            model_name='historicaltrungtam',
            name='ten',
            field=models.CharField(max_length=100, verbose_name='Tên Trung tâm'),
        ),
        migrations.AlterField(
            model_name='hsgv',
            name='ghichu',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hsns',
            name='ghichu',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='ghichu',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loaidiem',
            name='heso',
            field=models.IntegerField(default=1, verbose_name='Hệ số'),
        ),
        migrations.AlterField(
            model_name='loaidiem',
            name='trunglap',
            field=models.IntegerField(default=1, verbose_name='Số lần cho điểm'),
        ),
        migrations.AlterField(
            model_name='lop',
            name='ctdt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.ctdt', verbose_name='Chương trình đào tạo'),
        ),
        migrations.AlterField(
            model_name='lop',
            name='ma',
            field=models.CharField(max_length=100, verbose_name='Mã Lớp'),
        ),
        migrations.AlterField(
            model_name='lop',
            name='ten',
            field=models.CharField(max_length=100, verbose_name='Tên Lớp'),
        ),
        migrations.AlterField(
            model_name='lop',
            name='trungtam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.trungtam', verbose_name='Trung tâm'),
        ),
        migrations.AlterField(
            model_name='lophk',
            name='end_hk',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='lophk',
            name='hk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms.hocky', verbose_name='Học kỳ'),
        ),
        migrations.AlterField(
            model_name='lophk',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms.lop'),
        ),
        migrations.AlterField(
            model_name='lophk',
            name='start_hk',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Hồ sơ đào tạo'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt1',
            field=models.BooleanField(default=False, verbose_name='Hồ sơ đào tạo 1'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt2',
            field=models.BooleanField(default=False, verbose_name='Hồ sơ đào tạo 2'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt3',
            field=models.BooleanField(default=False, verbose_name='Hồ sơ đào tạo 3'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt4',
            field=models.BooleanField(default=False, verbose_name='Hồ sơ đào tạo 4'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='ngayend',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='ngaystart',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='trungtam',
            name='ma',
            field=models.IntegerField(default=1, verbose_name='Mã Trung tâm'),
        ),
        migrations.AlterField(
            model_name='trungtam',
            name='ten',
            field=models.CharField(max_length=100, verbose_name='Tên Trung tâm'),
        ),
        migrations.AlterUniqueTogether(
            name='ctdt',
            unique_together={('ten',)},
        ),
        migrations.AlterUniqueTogether(
            name='hocky',
            unique_together={('ma',)},
        ),
        migrations.AlterUniqueTogether(
            name='hocphistatus',
            unique_together={('ma',)},
        ),
        migrations.AlterUniqueTogether(
            name='loaidiem',
            unique_together={('ma',)},
        ),
        migrations.AlterUniqueTogether(
            name='lop',
            unique_together={('ma',)},
        ),
        migrations.AlterUniqueTogether(
            name='lophk',
            unique_together={('lop', 'hk')},
        ),
        migrations.AlterUniqueTogether(
            name='lopmonhoc',
            unique_together={('lop', 'monhoc')},
        ),
        migrations.AlterUniqueTogether(
            name='monhoc',
            unique_together={('ma', 'ten', 'chuongtrinh')},
        ),
        migrations.AlterUniqueTogether(
            name='phong',
            unique_together={('ma',)},
        ),
        migrations.AlterUniqueTogether(
            name='svstatus',
            unique_together={('ma',)},
        ),
        migrations.AlterUniqueTogether(
            name='trungtam',
            unique_together={('ma',)},
        ),
    ]
