# Generated by Django 4.2 on 2025-10-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_alter_historicalhouserenter_ghichu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhouserenter',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Đang thuê'),
        ),
        migrations.AddField(
            model_name='houserenter',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Đang thuê'),
        ),
    ]
