# Generated by Django 4.2 on 2025-05-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_alter_diemtk_tbmc_alter_historicaldiemtk_tbmc'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemtk',
            name='hk_id',
            field=models.IntegerField(default=1, verbose_name='Mã lớp môn học'),
        ),
        migrations.AddField(
            model_name='historicaldiemtk',
            name='hk_id',
            field=models.IntegerField(default=1, verbose_name='Mã lớp môn học'),
        ),
    ]
