# Generated by Django 4.2 on 2025-01-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_hssv_msv_alter_hssv_status_alter_lopmonhoc_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LopHk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hk', models.DateField(blank=True, default=None)),
                ('end_hk', models.DateField(blank=True, default=None)),
                ('hk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hocky')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.lop')),
            ],
        ),
    ]
