# Generated by Django 4.2 on 2025-03-15 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0010_alter_ctdt_options_alter_diemthanhphan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnslop',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Nhân sự lớp', 'verbose_name_plural': 'historical Danh sác Nhân sự lớp'},
        ),
        migrations.AlterModelOptions(
            name='nslop',
            options={'ordering': ['-id'], 'verbose_name': 'Nhân sự lớp', 'verbose_name_plural': 'Danh sác Nhân sự lớp'},
        ),
        migrations.RemoveField(
            model_name='historicalhsns',
            name='phong',
        ),
        migrations.RemoveField(
            model_name='hsns',
            name='phong',
        ),
        migrations.AlterUniqueTogether(
            name='nslop',
            unique_together={('ns', 'lop')},
        ),
        migrations.CreateModel(
            name='HistoricalNsPhong',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ns', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.hsns')),
                ('phong', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.phong')),
            ],
            options={
                'verbose_name': 'historical Nhân sự phòng',
                'verbose_name_plural': 'historical Danh sác Nhân sự phòng',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NsPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('ns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hsns')),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.phong')),
            ],
            options={
                'verbose_name': 'Nhân sự phòng',
                'verbose_name_plural': 'Danh sác Nhân sự phòng',
                'ordering': ['-id'],
                'unique_together': {('ns', 'phong')},
            },
        ),
    ]
