# Generated by Django 4.2 on 2025-11-02 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_historicalhouserenter_active_houserenter_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouse',
            name='deposit',
            field=models.CharField(verbose_name='Tiền đặt cọc (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='permonth',
            field=models.CharField(verbose_name='Tiền thuê/tháng (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='ten',
            field=models.CharField(default=' ', max_length=100, verbose_name='Tên nhà trọ'),
        ),
        migrations.AlterField(
            model_name='historicalhouserenter',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Hợp đồng đang có hiệu lực?'),
        ),
        migrations.AlterField(
            model_name='historicalhouserenter',
            name='renter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.renter', verbose_name='Người thuê'),
        ),
        migrations.AlterField(
            model_name='house',
            name='deposit',
            field=models.CharField(verbose_name='Tiền đặt cọc (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='permonth',
            field=models.CharField(verbose_name='Tiền thuê/tháng (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='ten',
            field=models.CharField(default=' ', max_length=100, verbose_name='Tên nhà trọ'),
        ),
        migrations.AlterField(
            model_name='houserenter',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Hợp đồng đang có hiệu lực?'),
        ),
        migrations.AlterField(
            model_name='houserenter',
            name='renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.renter', verbose_name='Người thuê'),
        ),
    ]
