# Generated by Django 4.2 on 2025-05-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_diemtk_hk_id_historicaldiemtk_hk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemtk',
            name='mhdk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldiemtk',
            name='mhdk',
            field=models.BooleanField(default=False),
        ),
    ]
