# Generated by Django 4.2 on 2025-03-15 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_alter_historicalnslop_options_alter_nslop_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctdtmonhoc',
            name='hocky',
        ),
        migrations.RemoveField(
            model_name='historicalctdtmonhoc',
            name='hocky',
        ),
        migrations.AddField(
            model_name='historicallopmonhoc',
            name='hk',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.hocky'),
        ),
        migrations.AddField(
            model_name='lopmonhoc',
            name='hk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.hocky'),
        ),
    ]
