# Generated by Django 4.2 on 2025-11-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_alter_historicalhouse_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouse',
            name='ten',
            field=models.CharField(max_length=100, verbose_name='Tên nhà trọ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='ten',
            field=models.CharField(max_length=100, verbose_name='Tên nhà trọ'),
        ),
    ]
