# Generated by Django 4.2 on 2025-11-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_alter_historicalhouse_ten_alter_house_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouse',
            name='deposit',
            field=models.IntegerField(verbose_name='Tiền đặt cọc (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='historicalhouse',
            name='permonth',
            field=models.IntegerField(verbose_name='Tiền thuê/tháng (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='deposit',
            field=models.IntegerField(verbose_name='Tiền đặt cọc (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='permonth',
            field=models.IntegerField(verbose_name='Tiền thuê/tháng (VNĐ)'),
        ),
    ]
