# Generated by Django 4.2 on 2025-03-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_nslop_historicalnslop'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalphong',
            name='ma',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicaltrungtam',
            name='ma',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='phong',
            name='ma',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trungtam',
            name='ma',
            field=models.IntegerField(default=1),
        ),
    ]
