# Generated by Django 4.2 on 2025-03-15 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0012_remove_ctdtmonhoc_hocky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctdtmonhoc',
            options={'ordering': ['ctdt', '-monhoc'], 'verbose_name': 'Chương trình đào tạo môn học', 'verbose_name_plural': 'Chương trình đào tạo môn học'},
        ),
        migrations.AlterUniqueTogether(
            name='ctdtmonhoc',
            unique_together={('ctdt', 'monhoc')},
        ),
        migrations.CreateModel(
            name='HistoricalGvMonhoc',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gv', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.hsgv')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('monhoc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.monhoc')),
            ],
            options={
                'verbose_name': 'historical Gíao viên Môn học   ',
                'verbose_name_plural': 'historical Danh sác Giao viên Môn học',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGvLop',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gv', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.hsgv')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lop', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.lop')),
            ],
            options={
                'verbose_name': 'historical Gíao viên lớp',
                'verbose_name_plural': 'historical Danh sác Giao viên lớp',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GvMonhoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hsgv')),
                ('monhoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.monhoc')),
            ],
            options={
                'verbose_name': 'Gíao viên Môn học   ',
                'verbose_name_plural': 'Danh sác Giao viên Môn học',
                'ordering': ['-id'],
                'unique_together': {('gv', 'monhoc')},
            },
        ),
        migrations.CreateModel(
            name='GvLop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hsgv')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.lop')),
            ],
            options={
                'verbose_name': 'Gíao viên lớp',
                'verbose_name_plural': 'Danh sác Giao viên lớp',
                'ordering': ['-id'],
                'unique_together': {('gv', 'lop')},
            },
        ),
    ]
