# Generated by Django 4.2 on 2025-01-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_historicalsvstatus_historicalloaidiem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lop',
            name='mhs',
            field=models.ManyToManyField(blank=True, default=None, to='sms.monhoc'),
        ),
    ]
