# Generated by Django 4.2 on 2025-03-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_historicalphong_ma_historicaltrungtam_ma_phong_ma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhssv',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hssv',
            name='image',
        ),
    ]
