# Generated by Django 4.2 on 2025-11-02 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0013_alter_historicalhouse_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoadon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, verbose_name='Mô tả hóa đơn')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo hóa đơn')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật hóa đơn')),
                ('duedate', models.DateField(verbose_name='Ngày đến hạn')),
                ('tienthuenha', models.IntegerField(blank=True, null=True, verbose_name='Tiền thuê/tháng (VNĐ)')),
                ('tiendien', models.IntegerField(blank=True, null=True, verbose_name='Tiền điện (VNĐ)')),
                ('tiennuoc', models.IntegerField(blank=True, null=True, verbose_name='Tiền nước (VNĐ)')),
                ('tienkhac', models.IntegerField(blank=True, null=True, verbose_name='Tiền khác (VNĐ)')),
                ('TONG_CONG', models.IntegerField(blank=True, null=True, verbose_name='TỔNG CỘNG PHẢI THU')),
                ('SO_TIEN_DA_TRA', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số tiền đã trả')),
                ('CONG_NO', models.IntegerField(blank=True, default=0, null=True, verbose_name='Công nợ')),
                ('status', models.CharField(choices=[('ChuaTT', 'Chưa thanh toán'), ('DangTT', 'Đang thanh toán (Công nợ)'), ('DaTT', 'Đã thanh toán'), ('QuaHan', 'Quá hạn')], default='ChuaTT', max_length=10, verbose_name='Trạng thái')),
                ('ghichu', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ghi chú')),
                ('house', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.house')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Danh mục Hóa đơn',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='historicaluploadedfile',
            name='link_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaluploadedfile',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='link_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Thanhtoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, verbose_name='Mô tả thanh toán')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo thanh toán')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật thanh toán')),
                ('tientt', models.IntegerField(blank=True, null=True, verbose_name='Số tiền (VNĐ)')),
                ('ghichu', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ghi chú')),
                ('hoadon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.hoadon')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Danh mục Thanh toán',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalThanhtoan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, verbose_name='Mô tả thanh toán')),
                ('ngay_tao', models.DateTimeField(blank=True, editable=False, verbose_name='Ngày tạo thanh toán')),
                ('ngay_cap_nhat', models.DateTimeField(blank=True, editable=False, verbose_name='Ngày cập nhật thanh toán')),
                ('tientt', models.IntegerField(blank=True, null=True, verbose_name='Số tiền (VNĐ)')),
                ('ghichu', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ghi chú')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hoadon', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.hoadon')),
            ],
            options={
                'verbose_name': 'historical Thanh toán',
                'verbose_name_plural': 'historical Danh mục Thanh toán',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHoadon',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, verbose_name='Mô tả hóa đơn')),
                ('ngay_tao', models.DateTimeField(blank=True, editable=False, verbose_name='Ngày tạo hóa đơn')),
                ('ngay_cap_nhat', models.DateTimeField(blank=True, editable=False, verbose_name='Ngày cập nhật hóa đơn')),
                ('duedate', models.DateField(verbose_name='Ngày đến hạn')),
                ('tienthuenha', models.IntegerField(blank=True, null=True, verbose_name='Tiền thuê/tháng (VNĐ)')),
                ('tiendien', models.IntegerField(blank=True, null=True, verbose_name='Tiền điện (VNĐ)')),
                ('tiennuoc', models.IntegerField(blank=True, null=True, verbose_name='Tiền nước (VNĐ)')),
                ('tienkhac', models.IntegerField(blank=True, null=True, verbose_name='Tiền khác (VNĐ)')),
                ('TONG_CONG', models.IntegerField(blank=True, null=True, verbose_name='TỔNG CỘNG PHẢI THU')),
                ('SO_TIEN_DA_TRA', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số tiền đã trả')),
                ('CONG_NO', models.IntegerField(blank=True, default=0, null=True, verbose_name='Công nợ')),
                ('status', models.CharField(choices=[('ChuaTT', 'Chưa thanh toán'), ('DangTT', 'Đang thanh toán (Công nợ)'), ('DaTT', 'Đã thanh toán'), ('QuaHan', 'Quá hạn')], default='ChuaTT', max_length=10, verbose_name='Trạng thái')),
                ('ghichu', models.TextField(blank=True, max_length=500, null=True, verbose_name='Ghi chú')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.house')),
            ],
            options={
                'verbose_name': 'historical Hóa đơn',
                'verbose_name_plural': 'historical Danh mục Hóa đơn',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
