# Generated by Django 4.2 on 2025-03-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_alter_ctdtmonhoc_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diemdanh',
            options={'verbose_name': 'Điểm danh', 'verbose_name_plural': 'Danh sách Điểm danh'},
        ),
        migrations.AlterModelOptions(
            name='historicaldiemdanh',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Điểm danh', 'verbose_name_plural': 'historical Danh sách Điểm danh'},
        ),
        migrations.AlterModelOptions(
            name='historicalhp81',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Học phí 81', 'verbose_name_plural': 'historical Danh sách Học phí 81'},
        ),
        migrations.AlterModelOptions(
            name='historicalhs81',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Hồ sơ 81', 'verbose_name_plural': 'historical Danh sách Hồ sơ 81'},
        ),
        migrations.AlterModelOptions(
            name='historicalhsgv',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Giáo viên', 'verbose_name_plural': 'historical Danh sách Giáo viên'},
        ),
        migrations.AlterModelOptions(
            name='historicalhsns',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Nhân sự', 'verbose_name_plural': 'historical Danh sách Nhân sự'},
        ),
        migrations.AlterModelOptions(
            name='historicalhssv',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Học viên', 'verbose_name_plural': 'historical Danh sách học viên'},
        ),
        migrations.AlterModelOptions(
            name='historicallichhoc',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Lịch học', 'verbose_name_plural': 'historical Danh sách Lịch học'},
        ),
        migrations.AlterModelOptions(
            name='historicalttgv',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Thanh toán giáo viên', 'verbose_name_plural': 'historical Danh sách Thanh toán giáo viên'},
        ),
        migrations.AlterModelOptions(
            name='hp81',
            options={'ordering': ['-sv', '-hk'], 'verbose_name': 'Học phí 81', 'verbose_name_plural': 'Danh sách Học phí 81'},
        ),
        migrations.AlterModelOptions(
            name='hs81',
            options={'ordering': ['-sv', '-hk'], 'verbose_name': 'Hồ sơ 81', 'verbose_name_plural': 'Danh sách Hồ sơ 81'},
        ),
        migrations.AlterModelOptions(
            name='hsgv',
            options={'ordering': ['ma'], 'verbose_name': 'Giáo viên', 'verbose_name_plural': 'Danh sách Giáo viên'},
        ),
        migrations.AlterModelOptions(
            name='hsns',
            options={'ordering': ['ma'], 'verbose_name': 'Nhân sự', 'verbose_name_plural': 'Danh sách Nhân sự'},
        ),
        migrations.AlterModelOptions(
            name='hssv',
            options={'ordering': ['msv'], 'verbose_name': 'Học viên', 'verbose_name_plural': 'Danh sách học viên'},
        ),
        migrations.AlterModelOptions(
            name='lichhoc',
            options={'ordering': ['thoigian'], 'verbose_name': 'Lịch học', 'verbose_name_plural': 'Danh sách Lịch học'},
        ),
        migrations.AlterModelOptions(
            name='ttgv',
            options={'ordering': ['-gv', '-lopmh'], 'verbose_name': 'Thanh toán giáo viên', 'verbose_name_plural': 'Danh sách Thanh toán giáo viên'},
        ),
        migrations.AlterUniqueTogether(
            name='diemdanh',
            unique_together={('sv', 'lichhoc')},
        ),
        migrations.AlterUniqueTogether(
            name='hp81',
            unique_together={('sv', 'hk')},
        ),
        migrations.AlterUniqueTogether(
            name='hs81',
            unique_together={('sv', 'hk')},
        ),
        migrations.AlterUniqueTogether(
            name='hsgv',
            unique_together={('ma',)},
        ),
        migrations.AlterUniqueTogether(
            name='hsns',
            unique_together={('ma',)},
        ),
        migrations.AlterUniqueTogether(
            name='hssv',
            unique_together={('msv',)},
        ),
        migrations.AlterUniqueTogether(
            name='ttgv',
            unique_together={('gv', 'lopmh')},
        ),
    ]
