# Generated by Django 4.2 on 2025-03-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_alter_diemdanh_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallopmonhoc',
            name='hsdt5',
            field=models.BooleanField(default=False, verbose_name='Danh sách học sinh ký thi'),
        ),
        migrations.AddField(
            model_name='historicallopmonhoc',
            name='hsdt6',
            field=models.BooleanField(default=False, verbose_name='Bài thi'),
        ),
        migrations.AddField(
            model_name='historicallopmonhoc',
            name='hsdt7',
            field=models.BooleanField(default=False, verbose_name='Đề thi/đáp án'),
        ),
        migrations.AddField(
            model_name='lopmonhoc',
            name='hsdt5',
            field=models.BooleanField(default=False, verbose_name='Danh sách học sinh ký thi'),
        ),
        migrations.AddField(
            model_name='lopmonhoc',
            name='hsdt6',
            field=models.BooleanField(default=False, verbose_name='Bài thi'),
        ),
        migrations.AddField(
            model_name='lopmonhoc',
            name='hsdt7',
            field=models.BooleanField(default=False, verbose_name='Đề thi/đáp án'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Xác nhận giảng dạy'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt1',
            field=models.BooleanField(default=False, verbose_name=' Tiến độ, kế hoạch, CTĐT'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt2',
            field=models.BooleanField(default=False, verbose_name='Phiếu báo giảng'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt3',
            field=models.BooleanField(default=False, verbose_name='Giáo án'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt4',
            field=models.BooleanField(default=False, verbose_name='Sổ tay giảng viên'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Xác nhận giảng dạy'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt1',
            field=models.BooleanField(default=False, verbose_name=' Tiến độ, kế hoạch, CTĐT'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt2',
            field=models.BooleanField(default=False, verbose_name='Phiếu báo giảng'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt3',
            field=models.BooleanField(default=False, verbose_name='Giáo án'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt4',
            field=models.BooleanField(default=False, verbose_name='Sổ tay giảng viên'),
        ),
    ]
