# Generated by Django 4.2 on 2025-03-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_remove_historicalhssv_image_remove_hssv_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallopmonhoc',
            name='hsdt1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicallopmonhoc',
            name='hsdt2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicallopmonhoc',
            name='hsdt3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicallopmonhoc',
            name='hsdt4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lopmonhoc',
            name='hsdt1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lopmonhoc',
            name='hsdt2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lopmonhoc',
            name='hsdt3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lopmonhoc',
            name='hsdt4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hsns',
            name='phong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.phong'),
        ),
    ]
