# Generated by Django 4.2 on 2025-11-03 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_hoadon_historicaluploadedfile_link_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thanhtoan',
            name='hoadon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.hoadon'),
        ),
    ]
