# Generated by Django 4.2 on 2025-01-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_lop_mhs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lop',
            name='mhs',
        ),
    ]
