# Generated by Django 4.2 on 2025-01-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_remove_lop_mhs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctdtmonhoc',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalctdtmonhoc',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
