# Generated by Django 4.2 on 2025-03-10 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_historicallopmonhoc_hsdt1_historicallopmonhoc_hsdt2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhp81',
            name='hs81_st',
        ),
        migrations.RemoveField(
            model_name='historicalhp81',
            name='thoigian',
        ),
        migrations.RemoveField(
            model_name='historicalhs81',
            name='bangtn',
        ),
        migrations.RemoveField(
            model_name='historicalhs81',
            name='dondn',
        ),
        migrations.RemoveField(
            model_name='historicalhs81',
            name='gks',
        ),
        migrations.RemoveField(
            model_name='historicalhs81',
            name='lop',
        ),
        migrations.RemoveField(
            model_name='hp81',
            name='hs81_st',
        ),
        migrations.RemoveField(
            model_name='hp81',
            name='thoigian',
        ),
        migrations.RemoveField(
            model_name='hs81',
            name='bangtn',
        ),
        migrations.RemoveField(
            model_name='hs81',
            name='dondn',
        ),
        migrations.RemoveField(
            model_name='hs81',
            name='gks',
        ),
        migrations.RemoveField(
            model_name='hs81',
            name='lop',
        ),
        migrations.AddField(
            model_name='historicalhs81',
            name='btn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalhs81',
            name='ddn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalhs81',
            name='thoigian',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='hs81',
            name='btn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hs81',
            name='ddn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hs81',
            name='thoigian',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='historicalhs81',
            name='cccd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalhs81',
            name='cccdbo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalhs81',
            name='cccdme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalhs81',
            name='cntn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalhs81',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalhs81',
            name='hk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.hocky'),
        ),
        migrations.AlterField(
            model_name='historicalhs81',
            name='status',
            field=models.CharField(choices=[('Thiếu', 'Thiếu'), ('Đủ', 'Đủ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalhs81',
            name='xnct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='cccd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='cccdbo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='cccdme',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='cntn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='hk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hocky'),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='status',
            field=models.CharField(choices=[('Thiếu', 'Thiếu'), ('Đủ', 'Đủ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='xnct',
            field=models.BooleanField(default=False),
        ),
    ]
