# Generated by Django 4.2 on 2025-03-16 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0015_historicallopmonhoc_hsdt5_historicallopmonhoc_hsdt6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Ghi chú Xác nhận giảng dạy'),
        ),
        migrations.AlterField(
            model_name='historicallopmonhoc',
            name='hsdt1',
            field=models.BooleanField(default=False, verbose_name='Tiến độ, kế hoạch, CTĐT'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Ghi chú Xác nhận giảng dạy'),
        ),
        migrations.AlterField(
            model_name='lopmonhoc',
            name='hsdt1',
            field=models.BooleanField(default=False, verbose_name='Tiến độ, kế hoạch, CTĐT'),
        ),
        migrations.CreateModel(
            name='Nganh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.IntegerField(default=1)),
                ('ten', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Ngành đào tạo',
                'verbose_name_plural': 'Danh mục Ngành đào tạo',
                'ordering': ['id'],
                'unique_together': {('ma',)},
            },
        ),
        migrations.CreateModel(
            name='Khoahoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.IntegerField(default=1)),
                ('ten', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Danh mục Khóa học',
                'ordering': ['id'],
                'unique_together': {('ma',)},
            },
        ),
        migrations.CreateModel(
            name='HistoricalNganh',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ma', models.IntegerField(default=1)),
                ('ten', models.CharField(max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ngành đào tạo',
                'verbose_name_plural': 'historical Danh mục Ngành đào tạo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalKhoahoc',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ma', models.IntegerField(default=1)),
                ('ten', models.CharField(max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Khóa học',
                'verbose_name_plural': 'historical Danh mục Khóa học',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHeDT',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ma', models.IntegerField(default=1)),
                ('ten', models.CharField(max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Hệ đào tạo',
                'verbose_name_plural': 'historical Danh mục Hệ đào tạo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HeDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.IntegerField(default=1)),
                ('ten', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Hệ đào tạo',
                'verbose_name_plural': 'Danh mục Hệ đào tạo',
                'ordering': ['id'],
                'unique_together': {('ma',)},
            },
        ),
    ]
