# Generated by Django 4.2 on 2025-11-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_alter_thanhtoan_hoadon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalhoadon',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical hoadon', 'verbose_name_plural': 'historical hoadons'},
        ),
        migrations.AlterModelOptions(
            name='hoadon',
            options={},
        ),
    ]
