# Generated by Django 4.2 on 2025-11-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_alter_historicalhoadon_options_alter_hoadon_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.house'),
        ),
    ]
