# Generated by Django 4.2 on 2025-03-17 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0016_alter_historicallopmonhoc_hsdt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGvLmh',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gv', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.hsgv')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lopmh', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.lopmonhoc')),
            ],
            options={
                'verbose_name': 'historical Giáo viên lớp môn học',
                'verbose_name_plural': 'historical Giáo viên lớp môn học',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GvLmh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hsgv')),
                ('lopmh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.lopmonhoc')),
            ],
            options={
                'verbose_name': 'Giáo viên lớp môn học',
                'verbose_name_plural': 'Giáo viên lớp môn học',
                'ordering': ['-gv', '-lopmh'],
                'unique_together': {('gv', 'lopmh')},
            },
        ),
    ]
