# Generated by Django 4.2 on 2025-03-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_remove_historicalhp81_hs81_st_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhs81',
            name='gks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hs81',
            name='gks',
            field=models.BooleanField(default=False),
        ),
    ]
