# Generated by Django 4.2 on 2025-11-03 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0017_alter_hoadon_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthanhtoan',
            name='status',
            field=models.CharField(choices=[('Choxn', 'Chờ xác nhận'), ('Daxn', 'Đã xác nhận'), ('Huy', 'Đã hủy')], default='Choxn', max_length=10, verbose_name='Trạng thái TT'),
        ),
        migrations.AddField(
            model_name='historicalthanhtoan',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='thanhtoan',
            name='status',
            field=models.CharField(choices=[('Choxn', 'Chờ xác nhận'), ('Daxn', 'Đã xác nhận'), ('Huy', 'Đã hủy')], default='Choxn', max_length=10, verbose_name='Trạng thái TT'),
        ),
        migrations.AddField(
            model_name='thanhtoan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
    ]
