# Generated by Django 4.2 on 2025-03-17 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_historicalgvlmh_gvlmh'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvlmh',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalgvlmh',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gvlmh',
            name='gv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.hsgv', verbose_name='Giáo viên'),
        ),
        migrations.AlterField(
            model_name='gvlmh',
            name='lopmh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.lopmonhoc', verbose_name='Lớp môn học'),
        ),
        migrations.AlterField(
            model_name='historicalgvlmh',
            name='gv',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.hsgv', verbose_name='Giáo viên'),
        ),
        migrations.AlterField(
            model_name='historicalgvlmh',
            name='lopmh',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.lopmonhoc', verbose_name='Lớp môn học'),
        ),
    ]
