# Generated by Django 4.2 on 2025-02-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_rename_gsk_historicalhs81_gks_rename_gsk_hs81_gks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhocphi',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalhs81',
            name='ghichu',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalhssv',
            name='ghichu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicallichhoc',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hocphi',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hs81',
            name='ghichu',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hssv',
            name='ghichu',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lichhoc',
            name='ghichu',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
