# Generated by Django 4.2 on 2025-03-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_gvlmh_status_historicalgvlmh_status_alter_gvlmh_gv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdiem',
            name='ten',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
