# Generated by Django 4.2 on 2025-03-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_logdiem_diemthanhphan_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloaidiem',
            name='heso',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalloaidiem',
            name='trunglap',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loaidiem',
            name='heso',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loaidiem',
            name='trunglap',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='diemthanhphan',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.logdiem'),
        ),
        migrations.AlterField(
            model_name='historicaldiemthanhphan',
            name='log',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.logdiem'),
        ),
    ]
