# Generated by Django 4.2 on 2025-11-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_historicalthanhtoan_status_historicalthanhtoan_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrenter',
            name='init_pwd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mật khẩu khởi tạo'),
        ),
        migrations.AddField(
            model_name='renter',
            name='init_pwd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mật khẩu khởi tạo'),
        ),
    ]
