# Generated by Django 4.2 on 2025-11-05 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0019_historicalrenter_init_pwd_renter_init_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhoadon',
            name='renter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sms.renter'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.renter'),
        ),
        migrations.AlterField(
            model_name='house',
            name='loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sms.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='chu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='xp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sms.xaphuong', verbose_name='Xã/Phường - Tỉnh/Thành phố'),
        ),
    ]
