# Generated by Django 4.2 on 2025-11-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0022_issuestatushistory_issueimage_issuecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('new', 'Mới'), ('in_progress', 'Đang xử lý'), ('pending_confirmation', 'Chờ xác nhận'), ('resolved', 'Đã xử lý'), ('rejected', 'Chưa xong')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='issuestatushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Mới'), ('in_progress', 'Đang xử lý'), ('pending_confirmation', 'Chờ xác nhận'), ('resolved', 'Đã xử lý'), ('rejected', 'Chưa xong')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issuestatushistory',
            name='old_status',
            field=models.CharField(choices=[('new', 'Mới'), ('in_progress', 'Đang xử lý'), ('pending_confirmation', 'Chờ xác nhận'), ('resolved', 'Đã xử lý'), ('rejected', 'Chưa xong')], max_length=20),
        ),
    ]
