# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0023_alter_issuereport_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sms.hoadon')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='sms.billcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.user')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
