# Generated by Django 4.2 on 2025-11-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0024_billcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('bill_created', 'Bill Created'), ('payment_submitted', 'Payment Submitted'), ('issue_reported', 'Issue Reported'), ('issue_resolved', 'Issue Resolved'), ('bill_commented', 'Bill Commented')], max_length=50),
        ),
    ]
