# Generated by Django 4.2 on 2025-11-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0025_alter_billcomment_id_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhoadon',
            name='qr_code_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='QR Code thanh toán'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='bill_qr_codes/', verbose_name='QR Code thanh toán'),
        ),
    ]
