# Generated by Django 4.2 on 2025-11-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0027_alter_renter_sdt_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='renter',
            unique_together={('hoten', 'chu_id')},
        ),
    ]
