# Generated by Django 4.2 on 2025-12-07 06:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0029_historicallandloard_landloard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalLandloard',
            new_name='HistoricalLandlord',
        ),
        migrations.RenameModel(
            old_name='Landloard',
            new_name='Landlord',
        ),
    ]
