# Generated by Django 4.2 on 2025-12-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0030_rename_historicallandloard_historicallandlord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouserenter',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Người thuê đang ở?'),
        ),
        migrations.AlterField(
            model_name='historicalrenter',
            name='noicap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nơi cấp'),
        ),
        migrations.AlterField(
            model_name='houserenter',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Người thuê đang ở?'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='noicap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nơi cấp'),
        ),
    ]
