# Generated by Django 4.2 on 2025-12-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_add_like_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_reply_images/'),
        ),
    ]
