# Generated by Django 4.2 on 2025-12-03 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_reply_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='image',
        ),
        migrations.CreateModel(
            name='ReplyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='forum_reply_images/')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.reply')),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='forum_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.forumpost')),
            ],
        ),
    ]
