# Generated by Django 5.1.7 on 2025-03-23 03:38

import datetime
import htmx_patterns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmx_patterns', '0004_monster_date_of_birth_monster_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, validators=[htmx_patterns.models.validate_not_future]),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(max_length=100, validators=[htmx_patterns.models.validate_no_title]),
        ),
        migrations.AlterField(
            model_name='monster',
            name='type',
            field=models.CharField(choices=[('humanoid', 'Humanoid'), ('blob', 'Blob'), ('leggy', 'Leggy')], help_text="Don't complain about the lack of choices", max_length=50),
        ),
    ]
