# Generated by Django 5.1.3 on 2024-12-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChamcongRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(blank=True, default='', max_length=300)),
                ('monhoc', models.CharField(blank=True, default='', max_length=300)),
                ('lop', models.CharField(blank=True, default='', max_length=300)),
                ('thoigian', models.DateField()),
                ('sogio', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='DiemdanhRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lop', models.CharField(blank=True, default='', max_length=300)),
                ('monhoc', models.CharField(blank=True, default='', max_length=300)),
                ('thoigian', models.DateField()),
                ('sv', models.CharField(blank=True, default='', max_length=300)),
                ('ghichu', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='HocphiRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(blank=True, default='', max_length=300)),
                ('lop', models.CharField(blank=True, default='', max_length=300)),
                ('sotien', models.IntegerField()),
            ],
        ),
    ]
