# Generated by Django 4.2 on 2025-03-20 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.class'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.course'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.teacher'),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.assign'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendanceclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='info.attendanceclass'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.student'),
        ),
        migrations.AlterField(
            model_name='attendanceclass',
            name='assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.assign'),
        ),
        migrations.AlterField(
            model_name='attendancetotal',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.course'),
        ),
        migrations.AlterField(
            model_name='attendancetotal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.dept'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.dept'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='studentcourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.studentcourse'),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.assign'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='info.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.course'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='info.student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='info.dept'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
